bundle:
  groupId: "io.jenkins.tools.war-packager.demo"
  artifactId: "pom-input-demo"
  vendor: "Jenkins project"
#  title: "Jenkins External Task Logging demo for Elasticsearch"
#  description: "Jenkins External Task Logging demo for Elasticsearch, packaged as a single WAR file. It automatically configures logging on startup"
buildSettings:
  docker:
    base: "jenkins/jenkins:2.121.1"
    tag: "jenkins/demo-pom-input"
    build: true
  pom: pom.xml
war:
  groupId: "org.jenkins-ci.main"
  artifactId: "jenkins-war"
  source:
    version: 2.121.1
systemProperties: {
    jenkins.model.Jenkins.slaveAgentPort: "9000",
    jenkins.model.Jenkins.slaveAgentPortEnforce: "true"}
#groovyHooks:
#  - type: "init"
#    id: "initScripts"
#    source:
#      dir: src/main/groovy
