bundle:
  groupId: "io.jenkins.tools.war-packager.demo"
  artifactId: "jenkins-external-task-logging-elk-demo"
  vendor: "Jenkins project"
  title: "Jenkins External Task Logging demo for Elasticsearch"
  description: "Jenkins External Task Logging demo for Elasticsearch, packaged as a single WAR file. It automatically configures logging on startup"
buildSettings:
  docker:
    base: "jenkins/jenkins:2.107.3"
    tag: "jenkins/demo-external-task-logging-elk"
    build: true
war:
  groupId: "org.jenkins-ci.main"
  artifactId: "jenkins-war"
  source:
    version: 2.107.3
plugins:
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "structs"
    source:
      version: 1.14
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "scm-api"
    source:
      version: 2.2.7
  - groupId: "org.jenkins-ci.plugins.workflow"
    artifactId: "workflow-aggregator"
    source:
      version: 2.5
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "durable-task"
    source:
      git: https://github.com/jglick/durable-task-plugin.git
      branch: watch-JENKINS-38381
  - groupId: "org.jenkins-ci.plugins.workflow"
    artifactId: "workflow-api"
    source:
      git: https://github.com/jglick/workflow-api-plugin.git
      branch: logs-JENKINS-38381
    build:
      buildOriginalVersion: true
  - groupId: "org.jenkins-ci.plugins.workflow"
    artifactId: "workflow-step-api"
    source:
      version: 2.15
  - groupId: "org.jenkins-ci.plugins.workflow"
    artifactId: "workflow-support"
    source:
      git: https://github.com/jglick/workflow-support-plugin.git
      branch: logs-JENKINS-38381
    build:
      buildOriginalVersion: true
  - groupId: "org.jenkins-ci.plugins.workflow"
    artifactId: "workflow-job"
    source:
      git: https://github.com/jglick/workflow-job-plugin.git
      branch: logs-JENKINS-38381
    build:
      buildOriginalVersion: true
  - groupId: "org.jenkins-ci.plugins.workflow"
    artifactId: "workflow-durable-task-step"
    source:
      git: https://github.com/jglick/workflow-durable-task-step-plugin.git
      branch: watch-JENKINS-38381
    build:
      buildOriginalVersion: true
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "logstash"
    source:
      git: https://github.com/jglick/logstash-plugin.git
      branch: logs-JENKINS-38381
  # Security warnings
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "junit"
    source:
      version: 1.24
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "mailer"
    source:
      version: 1.21
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "git-client"
    source:
      version: 2.7.2
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "credentials-binding"
    source:
      version: 1.16
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "docker-commons"
    source:
      version: 1.13
systemProperties: {
    jenkins.model.Jenkins.slaveAgentPort: "9000",
    jenkins.model.Jenkins.slaveAgentPortEnforce: "true"}
groovyHooks:
  - type: "init"
    id: "initScripts"
    source:
      dir: src/main/groovy
